### PR TITLE
Endpoints API

### PR DESCRIPTION
**Pull request by dsposito**
@cthos This should resolve issue #31.

The endpoints data format is similar to what you've [manually created](https://github.com/cthos/volcano-sdk-php/blob/master/routes.json) but with a few differences:
1. The main namespace ("seller", "customer", etc.) is lowercase - so the PHP and Python SDKs may need to be updated if we keep this lowercase convention.
2. The path vars are currently represented by a prepended dollar sign ($1, $2, etc). Would it be better (more language-agnostic) to use {1} instead as you implemented or some other format?
3. Should we use hyphenated names ("create-customer-contact") instead of lowerCamelCase ("createCustomerContact"). This is a trivial change but I'm wondering if something other than lowerCamelCase would be a better, language-agnostic format.
4. The main endpoints for the top level APIs (seller -> get, customer -> create, etc) have simple names ("get", "create", etc). Should we append the namespace name to make these more explicit (getSeller, createCustomer, etc.)?

If anyone has any thoughts on the above, please let us know!

Current Endpoints API output:

```
EDIT: Removed - see below for final output.
```

### CODE REVIEW

**Comment by dsposito** [comment]
@cthos Any thoughts on the above?

**Comment by cthos** [comment]
1) That's no problem, the formatter can str-to-lower everything.

2) I used {1} and whatnot since that's the convention Python uses for its `str.format` method, but I'd be fine with `$1` since that's the convention for various preg replacements.

3) I think that's a stylestic choice, though I think hyphenated words are probably the most popular.

4) I don't think it needs to change. It makes sense in a RESTFUL kind of way that you're referring to the HTTP Verb `GET` on the `seller` resource.

So, I think it's probably fine, as-is.

**Comment by cthos** [comment]
@dsposito - Here's the PR to get the php sdk ready for this change: https://github.com/cthos/volcano-sdk-php/pull/4

**Comment by dsposito** [comment]
@cthos Thanks for the feedback! I went ahead with the hyphenated endpoints names.

Here's the final output:

```
{
    "customer": {
        "create": {
            "method": "POST",
            "path": "api/customers/index"
        },
        "create-contact": {
            "method": "POST",
            "path": "api/customers/contacts/index/$1"
        },
        "create-order": {
            "method": "POST",
            "path": "api/customers/orders/index/$1"
        },
        "create-paymentmethod": {
            "method": "POST",
            "path": "api/customers/paymentmethods/index/$1"
        },
        "delete": {
            "method": "DELETE",
            "path": "api/customers/index/$1"
        },
        "delete-contact": {
            "method": "DELETE",
            "path": "api/customers/contacts/index/$1/$2"
        },
        "delete-paymentmethod": {
            "method": "DELETE",
            "path": "api/customers/paymentmethods/index/$1/$2"
        },
        "get": {
            "method": "GET",
            "path": "api/customers/index/$1"
        },
        "get-contact": {
            "method": "GET",
            "path": "api/customers/contacts/index/$1/$2"
        },
        "get-order": {
            "method": "GET",
            "path": "api/customers/orders/index/$1/$2"
        },
        "get-paymentmethod": {
            "method": "GET",
            "path": "api/customers/paymentmethods/index/$1/$2"
        },
        "get-product": {
            "method": "GET",
            "path": "api/customers/products/index/$1/$2"
        },
        "get-transaction": {
            "method": "GET",
            "path": "api/customers/transactions/index/$1/$2"
        },
        "list": {
            "method": "GET",
            "path": "api/customers/index"
        },
        "list-contact": {
            "method": "GET",
            "path": "api/customers/contacts/index/$1"
        },
        "list-order": {
            "method": "GET",
            "path": "api/customers/orders/index/$1"
        },
        "list-paymentmethod": {
            "method": "GET",
            "path": "api/customers/paymentmethods/index/$1"
        },
        "list-product": {
            "method": "GET",
            "path": "api/customers/products/index/$1"
        },
        "list-statistic-activity": {
            "method": "GET",
            "path": "api/customers/statistics/$1"
        },
        "list-statistic-conversion": {
            "method": "GET",
            "path": "api/customers/statistics/$1"
        },
        "list-statistic-totals": {
            "method": "GET",
            "path": "api/customers/statistics/$1"
        },
        "list-transaction": {
            "method": "GET",
            "path": "api/customers/transactions/index/$1"
        },
        "update": {
            "method": "PUT",
            "path": "api/customers/index/$1"
        },
        "update-contact": {
            "method": "PUT",
            "path": "api/customers/contacts/index/$1/$2"
        },
        "update-paymentmethod": {
            "method": "PUT",
            "path": "api/customers/paymentmethods/index/$1/$2"
        }
    },
    "endpoint": {
        "list": {
            "method": "GET",
            "path": "api/endpoints/index"
        }
    },
    "product": {
        "create": {
            "method": "POST",
            "path": "api/products/index"
        },
        "create-meta": {
            "method": "POST",
            "path": "api/products/metas/index/$1"
        },
        "create-meta-option": {
            "method": "POST",
            "path": "api/products/metas/options/index/$2"
        },
        "create-option": {
            "method": "POST",
            "path": "api/products/options/index/$1"
        },
        "create-option-fee": {
            "method": "POST",
            "path": "api/products/options/fees/index/$2"
        },
        "delete": {
            "method": "DELETE",
            "path": "api/products/index/$1"
        },
        "delete-option": {
            "method": "DELETE",
            "path": "api/products/options/index/$1/$2"
        },
        "delete-option-fee": {
            "method": "DELETE",
            "path": "api/products/options/fees/index/$2/$3"
        },
        "get": {
            "method": "GET",
            "path": "api/products/index/$1"
        },
        "get-meta": {
            "method": "GET",
            "path": "api/products/metas/index/$1/$2"
        },
        "get-meta-option": {
            "method": "GET",
            "path": "api/products/metas/options/index/$2/$3"
        },
        "get-option": {
            "method": "GET",
            "path": "api/products/options/index/$1/$2"
        },
        "get-option-fee": {
            "method": "GET",
            "path": "api/products/options/fees/index/$2/$3"
        },
        "list": {
            "method": "GET",
            "path": "api/products/index"
        },
        "list-meta": {
            "method": "GET",
            "path": "api/products/metas/index/$1"
        },
        "list-meta-option": {
            "method": "GET",
            "path": "api/products/metas/options/index/$2"
        },
        "list-option": {
            "method": "GET",
            "path": "api/products/options/index/$1"
        },
        "list-option-fee": {
            "method": "GET",
            "path": "api/products/options/fees/index/$2"
        },
        "update": {
            "method": "PUT",
            "path": "api/products/index/$1"
        },
        "update-meta": {
            "method": "PUT",
            "path": "api/products/metas/index/$1/$2"
        },
        "update-meta-option": {
            "method": "PUT",
            "path": "api/products/metas/options/index/$2/$3"
        },
        "update-option": {
            "method": "PUT",
            "path": "api/products/options/index/$1/$2"
        },
        "update-option-fee": {
            "method": "PUT",
            "path": "api/products/options/fees/index/$2/$3"
        }
    },
    "seller": {
        "create": {
            "method": "POST",
            "path": "api/sellers/index"
        },
        "create-callback": {
            "method": "POST",
            "path": "api/sellers/callbacks/index/$1"
        },
        "create-contact": {
            "method": "POST",
            "path": "api/sellers/contacts/index/$1"
        },
        "create-gateway": {
            "method": "POST",
            "path": "api/sellers/gateways/index/$1"
        },
        "delete-callback": {
            "method": "DELETE",
            "path": "api/sellers/callbacks/index/$1/$2"
        },
        "delete-contact": {
            "method": "DELETE",
            "path": "api/sellers/contacts/index/$1/$2"
        },
        "delete-gateway": {
            "method": "DELETE",
            "path": "api/sellers/gateways/index/$1/$2"
        },
        "get": {
            "method": "GET",
            "path": "api/sellers/index/$1"
        },
        "get-callback": {
            "method": "GET",
            "path": "api/sellers/callbacks/index/$1/$2"
        },
        "get-contact": {
            "method": "GET",
            "path": "api/sellers/contacts/index/$1/$2"
        },
        "get-gateway": {
            "method": "GET",
            "path": "api/sellers/gateways/index/$1/$2"
        },
        "list-callback": {
            "method": "GET",
            "path": "api/sellers/callbacks/index/$1"
        },
        "list-contact": {
            "method": "GET",
            "path": "api/sellers/contacts/index/$1"
        },
        "list-gateway": {
            "method": "GET",
            "path": "api/sellers/gateways/index/$1"
        },
        "update": {
            "method": "PUT",
            "path": "api/sellers/index/$1"
        },
        "update-callback": {
            "method": "PUT",
            "path": "api/sellers/callbacks/index/$1/$2"
        },
        "update-contact": {
            "method": "PUT",
            "path": "api/sellers/contacts/index/$1/$2"
        },
        "update-gateway": {
            "method": "PUT",
            "path": "api/sellers/gateways/index/$1/$2"
        }
    }
}
```

**Pull request merged**
